In [9]:
""""
Summarize fuel treatment acres within fire perimeters
Maxwell.Cook@colostate.edu
"""

# imports
import os, sys

# import the __functions.py (custom functions)
sys.path.append(os.getcwd()) # add code folder to system path
from __functions import *  # imports all custom functions

# local data directories
datadir = '/Users/mcc/Library/CloudStorage/Box-Box/MCC/data/'
projdir = os.path.dirname(os.getcwd())
print(projdir)

print("Ready !")

/Users/mcc/Library/CloudStorage/Box-Box/MCC/projects/valuation
Ready !

In [10]:
# read in the incidents data (gathered from the ICS209+ by Evan Herpe et al)
fp = os.path.join(projdir, "data/tabular/incidents/ics209plus-wf_incidents_2014_2022.csv")
incis = pd.read_csv(fp)
incis.head()

,Event_ID,irwinID,Incid_Name,Incid_Type,Map_ID,Map_Prog,Asmnt_Type,BurnBndAc,BurnBndLat,BurnBndLon,...,Increased Greenness.1,Non-Processing Mask.1,Total .1,Unburned to Low.2,Low.2,Moderate.2,High .2,Increased Greenness.2,Non-Processing Mask.2,Total .2
0,NJ3973407472120220619,400501E0-C028-41BA-BF7E-189BFAA0F876,MULLICA RIVER FIRE,Wildfire,10024293,MTBS,Initial,13082,39.689,-74.681,...,1%,4%,100%,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NC3565607641720220619,FF845212-7195-428F-88B5-1E904EA26003,FEREBEE ROAD,Wildfire,10024302,MTBS,Initial,1954,35.673,-76.427,...,0%,0%,100%,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,FL2576508042220220329,CFBFE97D-0AAB-4777-89DB-6C5AE68BA263,137 AVE,Wildfire,10024307,MTBS,Initial,857,25.769,-80.433,...,0%,0%,100%,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,FL2632608099820220328,07627D47-33EE-40C9-8773-DF8DDCF4D748,INTERCEPTOR,Wildfire,10024309,MTBS,Initial,4143,26.297,-81.059,...,0%,2%,100%,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,MS3143909088120220304,B946CEE6-A2AE-40D1-A6D5-312F22D1E10D,HWY 556 - BUDE MS,Wildfire,10024310,MTBS,Initial,663,31.447,-90.880,...,14%,0%,100%,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [3]:
len(incis)

3494

In [4]:
# load the data
nsi = pd.read_csv(os.path.join(projdir,"data/tabular/MTBS_NSI_summary.csv"))
twig = pd.read_csv(os.path.join(projdir, 'data/tabular/MTBS_TWIG_summary.csv'))

In [11]:
print(len(nsi) / len(incis) * 100)

38.6949055523755

In [12]:
nsi.columns

Index(['Incid_Name', 'MTBS_ID', 'val_struct_NR', 'val_struct_R', 'n_struct_NR',
       'n_struct_R', 'n_struct_total', 'prop_R'],
      dtype='object')

In [16]:
twig.columns

Index(['Event_ID', 'treated_acres_c', 'treated_prop_c', 'total_treatment_cost',
       'treated_prop_d', 'treated_acres_d', 'fire_buffer_acres'],
      dtype='object')

In [15]:
int(nsi['n_struct_total'].sum())

1352

In [5]:
# join the NSI attribute information
incis_nsi = pd.merge(incis, nsi, how='left', left_on='Event_ID', right_on='MTBS_ID')
len(incis_nsi)

3494

In [6]:
# merge in the twig data
incis_summary = pd.merge(incis_nsi, twig, how='left', on='Event_ID')
len(incis_summary)

3494

In [7]:
print(len(incis_summary) - incis_summary['treated_prop_d'].isna().sum())

1694

In [8]:
incis_summary

,Event_ID,irwinID,Incid_Name_x,Incid_Type,Map_ID,Map_Prog,Asmnt_Type,BurnBndAc,BurnBndLat,BurnBndLon,...,n_struct_NR,n_struct_R,n_struct_total,prop_R,treated_acres_c,treated_prop_c,total_treatment_cost,treated_prop_d,treated_acres_d,fire_buffer_acres
0,NJ3973407472120220619,400501E0-C028-41BA-BF7E-189BFAA0F876,MULLICA RIVER FIRE,Wildfire,10024293,MTBS,Initial,13082,39.689,-74.681,...,6.0,7.0,13.0,0.538462,NaN,NaN,NaN,NaN,NaN,NaN
1,NC3565607641720220619,FF845212-7195-428F-88B5-1E904EA26003,FEREBEE ROAD,Wildfire,10024302,MTBS,Initial,1954,35.673,-76.427,...,NaN,NaN,NaN,NaN,33.947103,1.737313,0.000000e+00,0.058991,14.253051,9223.417793
2,FL2576508042220220329,CFBFE97D-0AAB-4777-89DB-6C5AE68BA263,137 AVE,Wildfire,10024307,MTBS,Initial,857,25.769,-80.433,...,6.0,0.0,6.0,0.000000,NaN,NaN,NaN,NaN,NaN,NaN
3,FL2632608099820220328,07627D47-33EE-40C9-8773-DF8DDCF4D748,INTERCEPTOR,Wildfire,10024309,MTBS,Initial,4143,26.297,-81.059,...,0.0,1.0,1.0,1.000000,38351.960546,925.705058,0.000000e+00,4.238018,7841.344353,13390.910895
4,MS3143909088120220304,B946CEE6-A2AE-40D1-A6D5-312F22D1E10D,HWY 556 - BUDE MS,Wildfire,10024310,MTBS,Initial,663,31.447,-90.880,...,0.0,1.0,1.0,1.000000,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3489,WY4433510966920140723,DF599338-B6B8-4765-875A-DDC6B95DAD3A,SWEDE,Wildfire,23686,MTBS,Extended,1753,44.330,-109.645,...,NaN,NaN,NaN,NaN,2989.713585,170.548408,3.474919e+04,25.377956,2989.713585,11780.750217
3490,MT4711310778620140724,D62E7686-35FF-4C0A-AAAF-C15EDF902E50,CALF,Wildfire,21296,MTBS,Initial,1381,47.114,-107.791,...,NaN,NaN,NaN,NaN,658.499184,47.682779,0.000000e+00,2.961007,329.249592,11119.512744
3491,OK3598009917020140403,,CAMARGO,Wildfire,22062,MTBS,Initial (SS),7494,35.982,-99.186,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3492,CA3726811933420140728,47C63FE9-1726-4840-B183-9335D91A9029,FRENCH,Wildfire,22933,MTBS,Extended,14534,37.294,-119.360,...,NaN,NaN,NaN,NaN,157560.480154,1084.082016,2.617814e+07,0.267428,18937.956005,39802.922666
3493,OR4245612363620140913,1A60FE4B-C525-4C4F-9C92-7F9C49AE7E60,ONION MOUNTAIN,Wildfire,23252,MTBS,Extended,4063,42.466,-123.631,...,NaN,NaN,NaN,NaN,14694.304835,361.661453,3.680894e+06,0.001546,2225.971320,18576.970548